#!/usr/bin/env bash
# Real-world builtin benchmarks: JSON parse, naive string build (s += piece),
# and regex match. Unlike the integer kernels in run_bench.sh these run almost
# entirely inside Flaris's C builtins, so they measure the library paths users
# actually depend on. Every language reads the same generated input and must
# agree on the result integer.
#
# Normally invoked by run_bench.sh, which passes BENCH_REPORT/BENCH_APPEND so
# both halves land in one snapshot. Run it directly for a real-world-only
# snapshot of its own.
set -euo pipefail
cd "$(dirname "$0")"
BENCH_ROOT="$PWD"
source ./lib.sh

resolve_all_tools || exit 1
[[ -n "${BENCH_APPEND:-}" ]] || report_missing_tools

BENCH_TMP=$(mktemp -d "${TMPDIR:-/tmp}/flaris_bench_rw.XXXXXX")
trap 'rm -rf "$BENCH_TMP"' EXIT

mkdir -p "$BENCH_ROOT/results"
REPORT="${BENCH_REPORT:-$BENCH_ROOT/results/$(date +%Y-%m-%d)-$(machine_slug)-realworld.md}"

cd "$BENCH_ROOT/realworld"

# Lua and LuaJIT ship no stdlib JSON and only Lua patterns rather than full
# regex, so they take part in the string benchmark only.
JSON_LANGS=(py node js go nim fls flsj)
STR_LANGS=(py node js lua luajit go nim fls flsj)
REGEX_LANGS=(py node js go nim fls flsj)

# ── input data ───────────────────────────────────────────────────────────────
if [[ ! -f bench_data.json || ! -f bench_corpus.txt ]]; then
    [[ -n "$PYTHON" ]] || { warn "Python 3 is required to generate the benchmark input"; exit 1; }
    log "Generating benchmark input (~28 MB, deterministic)..."
    "$PYTHON" gen_bench_data.py
fi

# ── compile ──────────────────────────────────────────────────────────────────
if [[ -n "$GO" ]]; then
    log "Compiling Go..."
    for b in json strbuild regex; do
        "$GO" build -o "bench_${b}_go" "bench_${b}.go" || warn "Go: $b failed to build"
    done
fi
if [[ -n "$NIM" ]]; then
    log "Compiling Nim (-d:release --opt:speed -O3)..."
    for b in json strbuild regex; do
        "$NIM" c -d:release --opt:speed --passC:"-O3" --hints:off --warnings:off \
            -o:"bench_${b}_nim" "bench_${b}.nim" >/dev/null 2>&1 \
            || warn "Nim: $b failed to build"
    done
fi

# ── run ──────────────────────────────────────────────────────────────────────
run_lang() {  # run_lang <bench> <lang>
    local b="$1" l="$2" f
    case "$l" in
      py)     run_one "$b" py     "$PYTHON" "bench_${b}.py" ;;
      node)   run_one "$b" node   "$NODE"   "bench_${b}_node.js" ;;
      js)     run_one "$b" js     "$QJS"    "bench_${b}.js" ;;
      lua)    run_one "$b" lua    "$LUA"    "bench_${b}.lua" ;;
      luajit) run_one "$b" luajit "$LUAJIT" "bench_${b}.lua" ;;
      go)     f=$(bin_path "bench_${b}_go");  [[ -n "$f" ]] && run_one "$b" go  "$f" ;;
      nim)    f=$(bin_path "bench_${b}_nim"); [[ -n "$f" ]] && run_one "$b" nim "$f" ;;
      fls)    run_one "$b" fls    "$FLARISVM" --strip "bench_${b}.fls" ;;
      flsj)   run_one "$b" flsj   "$FLARISVM" --strip --jit "bench_${b}.fls" ;;
    esac
    return 0
}

log "Running json parse (18 MB, 5 iterations)..."
for l in "${JSON_LANGS[@]}";  do run_lang json "$l"; done
log "Running string build (naive s += piece, N=1,000,000)..."
for l in "${STR_LANGS[@]}";   do run_lang strbuild "$l"; done
log "Running regex match (9.8 MB corpus, 5 scans)..."
for l in "${REGEX_LANGS[@]}"; do run_lang regex "$l"; done

log "Checking result consistency..."
check_bench json     "${JSON_LANGS[@]}"
check_bench strbuild "${STR_LANGS[@]}"
check_bench regex    "${REGEX_LANGS[@]}"

# ── report ───────────────────────────────────────────────────────────────────
JSON_BASE=$(min_ms json "${JSON_LANGS[@]}")
STR_BASE=$(min_ms strbuild "${STR_LANGS[@]}")
REGEX_BASE=$(min_ms regex "${REGEX_LANGS[@]}")

{
if [[ -z "${BENCH_APPEND:-}" ]]; then
cat <<HEADER
# Flaris real-world benchmark results

**Date:** $(date +%Y-%m-%d)
**Machine:** $(cpu_name), $(os_name) ($(uname -m))
**Flaris VM:** $(flaris_version)

Generated by \`bench/run_bench_realworld.sh\`. Every number is $(runs_phrase),
measured inside the program. Lower is better.

HEADER
fi

cat <<'INTRO'
## Real-world builtins

These exercise the library paths users actually reach for - `Json.Parse`,
string concatenation and `Regex.Matches` - rather than pure integer kernels.
Every language reads identical generated input and returns the same result.

### 1. JSON parse - 18 MB array, 300k records, 5 iterations

Parse the same 18 MB document five times, summing every record's integer field.
Measures a JSON parser plus object/field materialisation. `result = 749,250,000`.

INTRO

emit_table json "$JSON_BASE" "vs fastest" 1 "${JSON_LANGS[@]}"

cat <<'STR'
### 2. String build - naive `s += piece`, N = 1,000,000

Grow a string one small piece at a time - the obvious, naive loop.
`result = 11,888,890` bytes. Go uses `strings.Builder`, Lua/LuaJIT use
`table.concat` and Nim uses `s.add`, because naive concatenation is quadratic
there; Python, Node, QuickJS and Flaris use the naive `s += piece` form.

STR

emit_table strbuild "$STR_BASE" "vs fastest" 1 "${STR_LANGS[@]}"

cat <<'REGEX'
### 3. Regex match - 9.8 MB corpus, 5 scans

Count every `\b\d{4}-\d{2}-\d{2}\b` date across a log-like corpus in which two
of every three lines are near-miss decoys. `result = 500,000`.

REGEX

emit_table regex "$REGEX_BASE" "vs fastest" 1 "${REGEX_LANGS[@]}"
} >> "$REPORT"

if [[ -z "${BENCH_APPEND:-}" ]]; then
cat >> "$REPORT" <<'METHOD'
## Methodology

- Times are wall-clock, measured inside the program; reading the input file is
  outside the timed region.
- Each figure is the median of several runs (`RUNS`, default 3).
- Every language must produce the same `result:` integer; the runner
  cross-checks them and warns on any disagreement.
- Input is generated by `realworld/gen_bench_data.py` and is byte-identical on
  every machine, so runs are comparable across hosts.
- Runtimes that are not installed are skipped and omitted from the tables.
- Peak RSS is measured from outside with `time(1)` and includes the runtime's
  own baseline, its JIT code cache and, where there is one, the
  garbage-collector heap high-water mark. The JSON benchmark is the meaningful
  one for memory: it materialises 300k records as live objects, so the column
  reflects the cost of the object representation rather than startup footprint.
METHOD
fi

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "  REAL-WORLD BUILTINS  (ms, lower is better)"
echo "═══════════════════════════════════════════════════════════════════"
printf "  %-12s %10s %12s %10s\n" "Language" "json" "strbuild" "regex"
for l in fls flsj py node js lua luajit go nim; do
    j=$(get_ms json "$l"); s=$(get_ms strbuild "$l"); r=$(get_ms regex "$l")
    [[ "$j" == "N/A" && "$s" == "N/A" && "$r" == "N/A" ]] && continue
    printf "  %-12s %8s ms %9s ms %7s ms\n" "$(lang_name "$l")" "$j" "$s" "$r"
done
echo "═══════════════════════════════════════════════════════════════════"

if [[ -n "$TIME_TOOL_MODE" ]]; then
    echo ""
    echo "  PEAK RSS  (MB, lower is better - includes runtime baseline)"
    printf "  %-12s %10s %12s %10s\n" "Language" "json" "strbuild" "regex"
    for l in fls flsj py node js lua luajit go nim; do
        j=$(get_mb json "$l"); s=$(get_mb strbuild "$l"); r=$(get_mb regex "$l")
        [[ "$j" == "N/A" && "$s" == "N/A" && "$r" == "N/A" ]] && continue
        printf "  %-12s %8s MB %9s MB %7s MB\n" "$(lang_name "$l")" "$j" "$s" "$r"
    done
    echo "═══════════════════════════════════════════════════════════════════"
fi
echo ""
log "Real-world results written - $REPORT"
