#!/usr/bin/env bash
# Integer-kernel benchmarks: recursive fib, sieve of Eratosthenes, Collatz.
# These are tight arithmetic and call-heavy loops with no library work, so they
# measure the VM dispatch loop itself rather than Flaris's C builtins - see
# run_bench_realworld.sh for the other half of the picture.
#
# Writes a dated snapshot to results/ and then hands off to the real-world
# runner, which appends its sections to the same file.
#
# Runtimes are discovered on PATH; override any of them by environment, e.g.
#   FLARISVM=../flarisvm LUA=~/src/lua-5.4.7/src/lua ./run_bench.sh
set -euo pipefail
cd "$(dirname "$0")"
BENCH_ROOT="$PWD"
source ./lib.sh

resolve_all_tools || exit 1
report_missing_tools

BENCH_TMP=$(mktemp -d "${TMPDIR:-/tmp}/flaris_bench.XXXXXX")
trap 'rm -rf "$BENCH_TMP"' EXIT

mkdir -p "$BENCH_ROOT/results"
REPORT="${BENCH_REPORT:-$BENCH_ROOT/results/$(date +%Y-%m-%d)-$(machine_slug).md}"

cd "$BENCH_ROOT/kernels"

# ── compile ──────────────────────────────────────────────────────────────────
if [[ -n "$CC" ]]; then
    log "Compiling C ($CC -O2)..."
    for b in fib sieve collatz; do
        "$CC" -O2 -o "bench_${b}_c" "bench_${b}.c" || warn "C: $b failed to build"
    done
fi
if [[ -n "$GO" ]]; then
    log "Compiling Go..."
    for b in fib sieve collatz; do
        "$GO" build -o "bench_${b}_go" "bench_${b}.go" || warn "Go: $b failed to build"
    done
fi
if [[ -n "$NIM" ]]; then
    log "Compiling Nim (-d:release --opt:speed -O3)..."
    for b in fib sieve collatz; do
        "$NIM" c -d:release --opt:speed --passC:"-O3" --hints:off --warnings:off \
            -o:"bench_${b}_nim" "bench_${b}.nim" >/dev/null 2>&1 \
            || warn "Nim: $b failed to build"
    done
fi

# ── run ──────────────────────────────────────────────────────────────────────
LANGS=(c go nim py lua luajit js fls flsj)

run_lang() {  # run_lang <bench> <lang>
    local b="$1" l="$2" f
    case "$l" in
      c)      f=$(bin_path "bench_${b}_c");   [[ -n "$f" ]] && run_one "$b" c   "$f" ;;
      go)     f=$(bin_path "bench_${b}_go");  [[ -n "$f" ]] && run_one "$b" go  "$f" ;;
      nim)    f=$(bin_path "bench_${b}_nim"); [[ -n "$f" ]] && run_one "$b" nim "$f" ;;
      py)     run_one "$b" py     "$PYTHON" "bench_${b}.py" ;;
      lua)    run_one "$b" lua    "$LUA"    "bench_${b}.lua" ;;
      luajit) f="bench_${b}.lua"; [[ -f "bench_${b}_jit.lua" ]] && f="bench_${b}_jit.lua"
              run_one "$b" luajit "$LUAJIT" "$f" ;;
      js)     run_one "$b" js     "$QJS"    "bench_${b}.js" ;;
      fls)    run_one "$b" fls    "$FLARISVM" --strip "bench_${b}.fls" ;;
      flsj)   run_one "$b" flsj   "$FLARISVM" --strip --jit "bench_${b}.fls" ;;
    esac
    return 0
}

log "Running fib(38)..."
for l in "${LANGS[@]}"; do run_lang fib "$l"; done
log "Running sieve(N=10M)..."
for l in "${LANGS[@]}"; do run_lang sieve "$l"; done
log "Running collatz(N=1M)..."
for l in "${LANGS[@]}"; do run_lang collatz "$l"; done

log "Checking result consistency..."
for b in fib sieve collatz; do check_bench "$b" "${LANGS[@]}"; done

# Mean of a language's three ×C ratios, as "<sortkey> <display>". A language
# with no usable ratio yields a key that sorts last instead of first.
kernel_avg() {   # kernel_avg <lang>
    awk -v a="$(ratio "$(get_ms fib "$1")" "$FIB_BASE")" \
        -v b="$(ratio "$(get_ms sieve "$1")" "$SIEVE_BASE")" \
        -v c="$(ratio "$(get_ms collatz "$1")" "$COLL_BASE")" 'BEGIN{
        n=0; sum=0
        gsub(/x$/,"",a); gsub(/x$/,"",b); gsub(/x$/,"",c)
        if(a!="N/A" && a+0>0){sum+=a+0; n++}
        if(b!="N/A" && b+0>0){sum+=b+0; n++}
        if(c!="N/A" && c+0>0){sum+=c+0; n++}
        if(n>0) printf "%.4f %.1fx", sum/n, sum/n; else printf "999999 N/A"
    }'
}

# ── report ───────────────────────────────────────────────────────────────────
FIB_BASE=$(get_ms fib c);     [[ "$FIB_BASE"  == "N/A" ]] && FIB_BASE=$(min_ms fib "${LANGS[@]}")
SIEVE_BASE=$(get_ms sieve c); [[ "$SIEVE_BASE" == "N/A" ]] && SIEVE_BASE=$(min_ms sieve "${LANGS[@]}")
COLL_BASE=$(get_ms collatz c);[[ "$COLL_BASE"  == "N/A" ]] && COLL_BASE=$(min_ms collatz "${LANGS[@]}")

{
cat <<HEADER
# Flaris benchmark results

**Date:** $(date +%Y-%m-%d)
**Machine:** $(cpu_name), $(os_name) ($(uname -m))
**Flaris VM:** $(flaris_version)

Generated by \`bench/run_bench.sh\`. Every number is $(runs_phrase),
measured inside the program, so process startup is excluded. Lower is better.
Interpretation of these numbers lives in [../README.md](../README.md).

## Toolchain

| Language | Version | Mode |
| -------- | ------- | ---- |
| C | $(tool_version "$CC" --version) | -O2 |
| Go | $(tool_version "$GO" version) | go build |
| Nim | $(tool_version "$NIM" --version) | -d:release --opt:speed -O3 |
| Python | $(tool_version "$PYTHON" --version) | CPython interpreted |
| Lua | $(tool_version "$LUA" -v) | interpreted |
| LuaJIT | $(tool_version "$LUAJIT" -v) | tracing JIT |
| Node | $(tool_version "$NODE" --version) | V8 |
| QuickJS | $(tool_version "$QJS" --help) | interpreted |
| Flaris | $(flaris_version) | bytecode VM (\`--strip\`) |

## Integer kernels

Pure arithmetic and control flow, no library calls. These measure the VM's
dispatch loop and JIT backend.

### 1. Recursive Fibonacci - \`fib(38)\` = 39,088,169

Roughly 126 M recursive calls. Measures function-call overhead and branch
prediction.

HEADER

emit_table fib "$FIB_BASE" "vs C" 0 "${LANGS[@]}"

cat <<'SIEVE'
### 2. Sieve of Eratosthenes - `N = 10,000,000`, 664,579 primes

Byte-array write-heavy inner loop. Tests memory bandwidth and array indexing
overhead. Each language uses its typed byte buffer (C `uint8_t*`, Nim
`seq[uint8]`, Python `bytearray`, JS `Uint8Array`, Lua table, Flaris `Buffer`).

SIEVE

emit_table sieve "$SIEVE_BASE" "vs C" 0 "${LANGS[@]}"

cat <<'COLLATZ'
### 3. Collatz total steps - `N = 1,000,000`

Sum of Collatz sequence lengths for n = 1…1 M, where each step is
`n = odd ? 3n+1 : n/2`. Data-dependent branching that cannot be vectorised.

COLLATZ

emit_table collatz "$COLL_BASE" "vs C" 0 "${LANGS[@]}"

cat <<'SUMMARY'
### Kernel summary

| Language | fib(38) | sieve(10M) | collatz(1M) | avg ×C |
| -------- | ------: | ---------: | ----------: | -----: |
SUMMARY

# Rows sorted by avg ×C so the summary reads as a ranking, like the
# per-benchmark tables above. The leading key is stripped after sorting;
# a language with no ratio at all sorts last rather than to the top.
for l in "${LANGS[@]}"; do
    f=$(get_ms fib "$l"); s=$(get_ms sieve "$l"); co=$(get_ms collatz "$l")
    [[ "$f" == "N/A" && "$s" == "N/A" && "$co" == "N/A" ]] && continue
    read -r key disp <<EOF
$(kernel_avg "$l")
EOF
    printf '%s\t| %s | %s ms | %s ms | %s ms | %s |\n' \
        "$key" "$(lang_name "$l")" "$f" "$s" "$co" "$disp"
done | sort -n | cut -f2-
echo ""
} > "$REPORT"

log "Kernel results written - $REPORT"

# ── console summary ──────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  INTEGER KERNELS  (ms, lower is better)"
echo "═══════════════════════════════════════════════════════════"
printf "  %-12s %10s %12s %13s %8s\n" "Language" "fib(38)" "sieve(10M)" "collatz(1M)" "avg xC"
for l in "${LANGS[@]}"; do
    f=$(get_ms fib "$l"); s=$(get_ms sieve "$l"); co=$(get_ms collatz "$l")
    [[ "$f" == "N/A" && "$s" == "N/A" && "$co" == "N/A" ]] && continue
    read -r key disp <<EOF
$(kernel_avg "$l")
EOF
    printf "%s\t  %-12s %8s ms %9s ms %10s ms %8s\n" \
        "$key" "$(lang_name "$l")" "$f" "$s" "$co" "$disp"
done | sort -n | cut -f2-
echo "═══════════════════════════════════════════════════════════"

if [[ -n "$TIME_TOOL_MODE" ]]; then
    echo ""
    echo "  PEAK RSS  (MB, lower is better - includes runtime baseline)"
    printf "  %-12s %10s %12s %13s\n" "Language" "fib(38)" "sieve(10M)" "collatz(1M)"
    for l in "${LANGS[@]}"; do
        f=$(get_mb fib "$l"); s=$(get_mb sieve "$l"); co=$(get_mb collatz "$l")
        [[ "$f" == "N/A" && "$s" == "N/A" && "$co" == "N/A" ]] && continue
        printf "  %-12s %8s MB %9s MB %10s MB\n" "$(lang_name "$l")" "$f" "$s" "$co"
    done
    echo "═══════════════════════════════════════════════════════════"
fi

# ── hand off to the real-world half, appending to the same snapshot ──────────
if [[ -x "$BENCH_ROOT/run_bench_realworld.sh" ]]; then
    echo ""
    BENCH_REPORT="$REPORT" BENCH_APPEND=1 "$BENCH_ROOT/run_bench_realworld.sh" \
        || warn "real-world benchmarks failed"
fi

cat >> "$REPORT" <<'METHOD'
## Methodology

- Times are wall-clock, measured inside the program with the language's own
  monotonic clock, so interpreter startup and input reading are never counted.
- Each figure is the median of several runs (`RUNS`, default 3).
- Every language must produce the same `result:` integer for a benchmark; the
  runner cross-checks them and warns on any disagreement.
- Flaris runs with `--strip` so debug metadata is not loaded, and appears twice:
  the plain bytecode VM, and `--jit` with the native backend enabled.
- Lua reports `os.clock()` (CPU time); everything else uses a wall clock. On an
  idle machine these agree for single-threaded work.
- Runtimes that are not installed are skipped and omitted from the tables
  rather than reported as zero.

### Reading the peak RSS column

Peak resident set size is measured from outside the process with `time(1)`, so
unlike the timings it **includes the runtime's own baseline** - interpreter,
JIT code cache, garbage-collector heap high-water mark and allocator arenas.
Two consequences worth keeping in mind:

- On the small integer kernels the figure is dominated by startup footprint,
  not by the benchmark. `fib` allocates essentially nothing, so that column is
  really "what does this runtime cost to have running at all".
- Runtimes with a tracing collector are measured at their heap high-water mark,
  which is a scheduling artefact as much as a workload property: a collector
  that runs less often looks worse here without being less efficient. Flaris
  uses reference counting over pre-allocated SLAB pools and has no tracing
  collector, so its figure tracks live data more directly than Go's or Node's.

The memory numbers are therefore best read within a row-group of similar
runtimes, and on the workloads that actually build a large object graph - the
JSON benchmark most of all - rather than as a single cross-language ranking.
METHOD

echo ""
log "Full snapshot - $REPORT"
